name: Read hello.txt on push to main

on:
  push:
    branches:
     - main

jobs:
  read-hello-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Read hello.txt
        run: |
          echo "Contents of hello.txt"
          cat hello.txt